# ~/.tmuxinator/Launcher.yml

name: main
root: .

windows:
  - server:
      - cd server
      - python3 server.py
  - filesystem:
      - sleep 3
      - cd fuse
      - make compile
      - cd fs
  <%- if args[0] == "psql" %>
  - database:
    - sleep 6
    - cd fuse
    - make psql
    - /usr/lib/postgresql/12/bin/initdb -D fs
    - /usr/lib/postgresql/12/bin/postgres -D fs -k. 
  <%- end %>